- name: Check if already installed
  stat:
    path: /etc/csf/
  register: csf

- include_tasks: "install.yml"
  when: not csf.stat.exists and macklus.configserver.csf.install|bool == true

- include_tasks: "configure.yml"
  when: macklus.configserver.csf.install|bool == true